#!/usr/bin/env python3
"""ELARA "two-bucket" PSU -- single source of truth for the schematic.

Goal: a mains supply as quiet as a battery.

  230 V AC -> Mean Well IRM-05-15 (charger side, GND_C, bonded to PE/enclosure)
           -> constant-current 0.2 A / constant-voltage 10.9 V supercap charger
           -> two supercapacitor "buckets" (4 x 10 F each)
           -> two DPDT form-C relays swap the buckets every ~30 s
           -> receiver side: reservoir -> LT3045 (0.8 uV rms) -> common-mode
              choke -> 8.45 V out

A form-C relay breaks before it makes, so a bucket is never connected to the
charger and the receiver at the same time: the receiver ground is
galvanically isolated from mains at every instant, and the only coupling left
is the ~1 pF across the open relay contacts (vs 20-100 pF across an AC-DC
module's barrier). The swap rate (17 mHz) is below the ELF band, and the
bucket droop / swap step is removed by the LT3045 and again by the ADM7150s
on the amplifier board. The charger side, its timer and relay coils live in
the grounded ALU PSU enclosure; there is no LED on the receiver side.

A 9-15 V battery on the amplifier's input connector replaces this whole unit.

Usage:  .venv/bin/python PCB/acdc_converter/design.py [--no-check]
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'tools'))

from kicadgen import schematic  # noqa: E402
from kicadgen.schematic import Project  # noqa: E402

NAME = 'acdc_converter'
schematic.POWER_SYMBOLS['GND_C'] = 'power:GNDD'   # charger-side ground (PE bonded)

R0805 = 'Resistor_SMD:R_0805_2012Metric'
C0805 = 'Capacitor_SMD:C_0805_2012Metric'
C1206 = 'Capacitor_SMD:C_1206_3216Metric'
R2512 = 'Resistor_SMD:R_2512_6332Metric'

ERA = {'100': '101V', '240': '241V', '1.87k': '1871V', '4.7k': '472V', '100k': '104V', '160k': '164V',
       '1M': '105V', '84.5k': '8452V'}


def pana(mpn, desc):
    return {'Manufacturer': 'Panasonic', 'MPN': mpn, 'Description': desc}


def mur(mpn, desc):
    return {'Manufacturer': 'Murata', 'MPN': mpn, 'Description': desc}


CAP_100N = mur('GRM21BR71H104KA01L', 'MLCC 100n 50V X7R 0805')
CAP_10U = mur('GRM31CR71E106KA12L', 'MLCC 10u 25V X7R 1206')


class Refs:
    def __init__(self):
        self.n = {}

    def __call__(self, prefix):
        self.n[prefix] = self.n.get(prefix, 0) + 1
        return f'{prefix}{self.n[prefix]}'


ref = Refs()


def R(sh, value, pos, a, b, rot=0, fp=R0805, fields=None):
    return sh.add(ref('R'), 'Device:R', value, pos, {1: a, 2: b}, rot=rot, footprint=fp,
                  fields=fields or pana(f'ERA-6AEB{ERA[value]}', f'Thin film {value} 0.1% 0805'))


def C(sh, value, pos, a, b, rot=0, fp=C0805, fields=CAP_100N, polar=False):
    return sh.add(ref('C'), 'Device:C_Polarized' if polar else 'Device:C', value, pos, {1: a, 2: b}, rot=rot,
                  footprint=fp, fields=fields)


def bucket(sh, name, x, y):
    """Four 10 F / 2.7 V EDLC cells in series, each with a passive balancing resistor.

    Cells (and resistors) are stacked so adjacent pins touch; each node is
    wired across to its balancing resistor.
    """
    nodes = [f'{name}_P', f'{name}_1', f'{name}_2', f'{name}_3', f'{name}_N']
    for i in range(4):
        C(sh, '10F', (x, y + i * 7.62), nodes[i], nodes[i + 1], polar=True,
          fp='Capacitor_THT:CP_Radial_D12.5mm_P5.00mm',
          fields={'Manufacturer': 'Eaton', 'MPN': 'HV1245-2R7106-R',
                  'Description': 'EDLC 10 F 2.7 V, D12.5 P5.0 (any 10 F 2.7 V radial cell; match within 5%)'})
        R(sh, '5.1k', (x + 12.7, y + i * 7.62), nodes[i], nodes[i + 1], fp='Resistor_SMD:R_1206_3216Metric',
          fields=pana('ERJ-8ENF5101V', 'Balancing 5k1 1% 1206 (~0.5 mA, >10x cell leakage)'))
    for i in range(5):
        yy = y - 3.81 + i * 7.62
        if 0 < i < 4:
            sh.wire((x, yy), (x + 12.7, yy))
            sh.label(nodes[i], (x + 6.35, yy))


def build():
    p = Project(NAME, HERE, 'ELARA PSU', rev='0.2', company='ELARA -- ELF Atmospheric Radio Analyser',
                comments=('CERN-OHL-W-2.0',
                          'Generated by PCB/acdc_converter/design.py -- edit the script, not the sheet',
                          'MAINS VOLTAGE on the primary side -- 6.4 mm creepage to everything else'))
    sh = p.sheet('psu', 'psu.kicad_sch', 'Two-bucket isolated supply')

    # ---- primary ---------------------------------------------------------
    sh.box(15, 20, 105, 100, 'MAINS  (primary)')
    sh.add('J1', 'Connector:Screw_Terminal_01x03', 'MAINS L N PE', (27.94, 45.72),
           {1: 'L_IN', 2: 'AC_N', 3: 'PE'}, mirror='y',
           footprint='TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-3-5.08_1x03_P5.08mm_Horizontal',
           fields={'Manufacturer': 'Phoenix Contact', 'MPN': '1715734',
                   'Description': 'Mains input: 1 L, 2 N, 3 PE'})
    sh.add('F1', 'Device:Fuse', 'T500mA', (55.88, 35.56), {1: 'L_IN', 2: 'AC_L'}, rot=90,
           footprint='Fuse:Fuseholder_Clip-5x20mm_Bel_FC-203-22_Lateral_P17.80x5.00mm_D1.17mm_Horizontal',
           fields={'Manufacturer': 'Bel Fuse', 'MPN': '5ST 500-R + 2x FC-203-22 clips',
                   'Description': 'Fuse 5x20 mm T500 mA 250 V slow-blow, in PCB clips'})
    sh.add('RV1', 'Device:Varistor', '275VAC', (86.36, 58.42), {1: 'AC_L', 2: 'AC_N'},
           footprint='Varistor:RV_Disc_D12mm_W4.7mm_P7.5mm',
           fields={'Manufacturer': 'TDK', 'MPN': 'B72210S0271K101',
                   'Description': 'MOV 275 VAC, mains surge clamp after the fuse'})
    for i in range(4):
        sh.add(f'H{i + 1}', 'Mechanical:MountingHole_Pad', 'M3 PE', (25.4 + i * 12.7, 86.36), {1: 'PE'},
               footprint='MountingHole:MountingHole_3.2mm_M3_Pad_Via',
               fields={'Manufacturer': '-', 'MPN': '-', 'Description': 'M3 hole bonded to PE (ALU enclosure)'})
    sh.flag('AC_L', (99.06, 38.1))
    sh.flag('AC_N', (99.06, 76.2))
    sh.flag('PE', (78.74, 86.36))

    sh.box(110, 20, 165, 100, 'AC-DC  15 V')
    sh.add('PS1', 'Converter_ACDC:IRM-05-15', 'IRM-05-15', (137.16, 55.88),
           {2: 'AC_L', 1: 'AC_N', 4: '+15V_C', 3: 'GND_C'},
           footprint='Converter_ACDC:Converter_ACDC_MeanWell_IRM-05-xx_THT',
           fields={'Manufacturer': 'Mean Well', 'MPN': 'IRM-05-15',
                   'Description': '5 W 15 V encapsulated AC-DC module, 3 kVAC, EN55032 class B'})
    R(sh, '0', (152.4, 86.36), 'GND_C', 'PE', fp='Resistor_SMD:R_1206_3216Metric',
      fields={'Manufacturer': 'Panasonic', 'MPN': 'ERJ-8GEY0R00V',
              'Description': 'Bonds charger ground to PE/enclosure: all switching noise stays in the grounded box'})

    # ---- charger side (GND_C) -------------------------------------------
    sh.box(170, 20, 405, 100, 'CHARGER  (GND_C)  CC 0.2 A -> CV 10.9 V')
    C(sh, '47u', (180.34, 58.42), '+15V_C', 'GND_C', polar=True, fp='Capacitor_THT:CP_Radial_D6.3mm_P2.50mm',
      fields=pana('EEU-FR1E470', 'Electrolytic 47u 25V low-ESR'))
    C(sh, '100n', (190.5, 58.42), '+15V_C', 'GND_C')
    sh.add('U1', 'Regulator_Linear:LM317_TO-220', 'LM317', (210.82, 38.1),
           {3: '+15V_C', 2: 'CC_SET', 1: 'CC_OUT'}, footprint='Package_TO_SOT_THT:TO-220-3_Vertical',
           fields={'Manufacturer': 'Texas Instruments', 'MPN': 'LM317KCSE3',
                   'Description': 'Constant current, 1.25 V / 6.2 R = 0.2 A (clip-on heatsink)'})
    R(sh, '6.2', (210.82, 60.96), 'CC_SET', 'CC_OUT', rot=90, fp=R2512,
      fields={'Manufacturer': 'Vishay', 'MPN': 'CRCW25126R20FKEG', 'Description': 'Current set 6R2 1% 1 W 2512'})
    sh.add('U2', 'Regulator_Linear:LM317_TO-220', 'LM317', (251.46, 38.1),
           {3: 'CC_OUT', 2: 'CHG', 1: 'CV_ADJ'}, footprint='Package_TO_SOT_THT:TO-220-3_Vertical',
           fields={'Manufacturer': 'Texas Instruments', 'MPN': 'LM317KCSE3',
                   'Description': 'Constant voltage 1.25 V x (1 + 1.87k/240) = 10.9 V'})
    R(sh, '240', (271.78, 58.42), 'CHG', 'CV_ADJ')
    R(sh, '1.87k', (271.78, 83.82), 'CV_ADJ', 'GND_C')
    C(sh, '10u', (284.48, 71.12), 'CHG', 'GND_C', fp=C1206, fields=CAP_10U)
    sh.add('D1', 'Diode:SS34', 'SS34', (302.26, 38.1), {1: 'CHG_D', 2: 'CHG'}, rot=180,
           footprint='Diode_SMD:D_SMA',
           fields={'Manufacturer': 'Vishay', 'MPN': 'SS34-E3/57T',
                   'Description': 'Stops the buckets discharging into the charger when mains is off'})
    sh.add('U3', 'Regulator_Linear:L78L12_SOT89', 'L78L12', (335.28, 38.1),
           {3: '+15V_C', 1: '+12V_C', 2: 'GND_C'}, footprint='Package_TO_SOT_SMD:SOT-89-3',
           fields={'Manufacturer': 'STMicroelectronics', 'MPN': 'L78L12ACUTR',
                   'Description': '12 V for relay coils and timer'})
    C(sh, '330n', (322.58, 60.96), '+15V_C', 'GND_C', fields=mur('GRM21BR71H334KA88L', 'MLCC 330n 50V X7R 0805'))
    C(sh, '100n', (347.98, 60.96), '+12V_C', 'GND_C')
    R(sh, '4.7k', (368.3, 45.72), '+12V_C', 'LED_C')
    sh.add('D2', 'Device:LED', 'GREEN', (368.3, 68.58), {2: 'LED_C', 1: 'GND_C'}, rot=90,
           footprint='LED_SMD:LED_0805_2012Metric',
           fields={'Manufacturer': 'Wurth', 'MPN': '150080VS75000',
                   'Description': 'LED green, mains present (charger side only)'})
    sh.flag('CC_OUT', (231.14, 53.34))

    # ---- swap timer -----------------------------------------------------
    sh.box(15, 105, 165, 195, 'SWAP TIMER  Q14 toggles every ~30 s')
    sh.add('U4', '4xxx:4060', 'CD4060B', (55.88, 147.32),
           {9: 'OSC_C', 10: 'OSC_R', 11: 'OSC_I', 12: 'GND_C', 16: '+12V_C', 8: 'GND_C',
            7: None, 5: None, 4: None, 6: None, 14: None, 13: None, 15: None, 1: None, 2: None, 3: 'SWAP'},
           footprint='Package_SO:SOIC-16_3.9x9.9mm_P1.27mm',
           fields={'Manufacturer': 'Texas Instruments', 'MPN': 'CD4060BM96',
                   'Description': '14-stage counter + RC oscillator, f = 1/(2.3 Rt Ct) = 272 Hz, Q14 = f/16384'})
    C(sh, '10n', (111.76, 124.46), 'OSC_C', 'OSC_X', rot=90,
      fields=mur('GRM2195C1H103JA01D', 'MLCC 10n 50V C0G 0805 (Ct)'))
    R(sh, '160k', (111.76, 139.7), 'OSC_R', 'OSC_X', rot=90)
    R(sh, '1M', (111.76, 154.94), 'OSC_I', 'OSC_X', rot=90)
    C(sh, '100n', (144.78, 177.8), '+12V_C', 'GND_C')

    sh.box(170, 105, 405, 195, 'BUCKET SWAP  (form C: break before make)')
    R(sh, '100', (187.96, 142.24), 'SWAP', 'GATE', rot=90)
    R(sh, '100k', (203.2, 160.02), 'GATE', 'GND_C')
    sh.add('Q1', 'Transistor_FET:2N7002', '2N7002', (220.98, 149.86), {1: 'GATE', 3: 'COIL_N', 2: 'GND_C'},
           footprint='Package_TO_SOT_SMD:SOT-23',
           fields={'Manufacturer': 'onsemi', 'MPN': '2N7002LT1G', 'Description': 'Relay coil driver'})
    for i, (k, nc_p, no_p, nc_n, no_n, bk) in enumerate((
            ('K1', 'CHG_A', 'LOAD_A', 'GND_C', 'GND', 'A'),
            ('K2', 'LOAD_B', 'CHG_B', 'GND', 'GND_C', 'B'))):
        x = 271.78 + i * 76.2
        sh.add(k, 'Relay:G6K-2', 'G6K-2F-Y DC12', (x, 147.32), labels_only=True, nets=
               {1: '+12V_C', 8: 'COIL_N', 3: f'{bk}_P', 2: nc_p, 4: no_p, 6: f'{bk}_N', 7: nc_n, 5: no_n},
               footprint='Relay_SMD:Relay_DPDT_Omron_G6K-2F-Y',
               fields={'Manufacturer': 'Omron', 'MPN': 'G6K-2F-Y DC12',
                       'Description': f'Bucket {bk} relay, DPDT 1 A; K2 is wired in the opposite sense to K1'})
        sh.add(f'D{3 + i}', 'Diode:1N4148W', '1N4148W', (x - 25.4, 172.72), {1: '+12V_C', 2: 'COIL_N'}, rot=90,
               footprint='Diode_SMD:D_SOD-123',
               fields={'Manufacturer': 'Diodes Inc.', 'MPN': '1N4148W-7-F', 'Description': 'Coil flyback diode'})
    for i, (net, dst) in enumerate((('CHG_A', 'CHG_D'), ('CHG_B', 'CHG_D'), ('LOAD_A', 'LOAD_P'), ('LOAD_B', 'LOAD_P'))):
        R(sh, '2.2', (190.5 + i * 27.94, 187.96), net, dst, rot=90, fp=R2512,
          fields={'Manufacturer': 'Vishay', 'MPN': 'CRCW25122R20FKEG',
                  'Description': 'Limits bucket-to-bucket current while both relays are mid-swap'})
    sh.flag('COIL_N', (241.3, 180.34))

    # ---- buckets ----------------------------------------------------------
    sh.box(15, 200, 67, 280, 'BUCKET A  2.5 F')
    bucket(sh, 'A', 30.48, 226.06)
    sh.box(72, 200, 124, 280, 'BUCKET B  2.5 F')
    bucket(sh, 'B', 87.63, 226.06)

    # ---- receiver side (GND) ------------------------------------------------
    sh.box(129, 200, 282, 280, 'RECEIVER SIDE  LT3045 8.45 V')
    C(sh, '2200u', (139.7, 243.84), 'LOAD_P', 'GND', polar=True, fp='Capacitor_THT:CP_Radial_D10.0mm_P5.00mm',
      fields=pana('EEU-FR1C222', 'Electrolytic 2200u 16V low-ESR, rides through the relay transit'))
    C(sh, '10u', (149.86, 243.84), 'LOAD_P', 'GND', fp=C1206, fields=CAP_10U)
    sh.add('U5', 'Regulator_Linear:LT3045xMSE', 'LT3045', (182.88, 233.68),
           {1: 'LOAD_P', 2: 'LOAD_P', 3: 'LOAD_P', 4: 'LOAD_P', 7: 'LOAD_P', 6: 'GND', 8: 'SET',
            9: 'GND', 13: 'GND', 11: 'VREG', 12: 'VREG', 10: 'VREG', 5: None},
           footprint='Package_SO:MSOP-12-1EP_3x4.039mm_P0.65mm_EP1.651x2.845mm_ThermalVias',
           fields={'Manufacturer': 'Analog Devices', 'MPN': 'LT3045EMSE#PBF',
                   'Description': 'Ultralow-noise LDO: EN and PGFB tied to IN (no fast start-up), ILIM to GND'})
    R(sh, '84.5k', (182.88, 264.16), 'SET', 'GND')
    C(sh, '22u', (195.58, 264.16), 'SET', 'GND', fp=C1206,
      fields=mur('GRM31CR71C226ME15L', 'MLCC 22u 16V X7R 1206 (C_SET: lowest 1/f noise, ~4 s soft start)'))
    C(sh, '10u', (215.9, 243.84), 'VREG', 'GND', fp=C1206, fields=CAP_10U)
    sh.add('L1', 'Device:Filter_EMI_CommonMode', 'CMC', (241.3, 223.52),
           {1: 'VREG', 2: '+9V_OUT', 3: 'GND', 4: 'OUT_N'},
           footprint='Inductor_SMD:L_CommonModeChoke_Bourns_SRF1260',
           fields={'Manufacturer': 'Bourns', 'MPN': 'SRF1260-102Y',
                   'Description': 'Common-mode choke 1 mH, keeps RF off the output cable'})
    sh.add('D5', 'Diode:SMAJ12A', 'SMAJ12A', (256.54, 262.89), {1: '+9V_OUT', 2: 'OUT_N'}, rot=270,
           footprint='Diode_SMD:D_SMA',
           fields={'Manufacturer': 'Littelfuse', 'MPN': 'SMAJ12A', 'Description': 'TVS 12 V, output clamp'})
    sh.add('J2', 'Connector_Generic:Conn_01x02', '9V OUT', (274.32, 241.3), {1: '+9V_OUT', 2: 'OUT_N'},
           footprint='Connector_Molex:Molex_Micro-Fit_3.0_43650-0200_1x02_P3.00mm_Horizontal',
           fields={'Manufacturer': 'Molex', 'MPN': '43650-0200',
                   'Description': 'Micro-Fit 3.0 2-pin, 8.45 V to the antenna amplifier (shielded pair)'})
    sh.flag('LOAD_P', (160.02, 271.78))
    sh.flag('GND', (231.14, 271.78))
    sh.flag('+9V_OUT', (243.84, 271.78))

    sh.text('Bucket: 2.5 F feeding ~0.11 A for 30 s droops ~1.3 V (10.6 -> 9.3 V); LT3045 needs 8.45 + 0.3 V. '
            'Swap rate 17 mHz, below the ELF band.', (15, 290), size=1.5)
    return p


def main():
    p = build()
    p.write()
    comps = [{'ref': pl.ref, 'value': pl.value, 'footprint': pl.footprint, 'lib_id': pl.sym.lib_id,
              'sheet': s.name, 'sheet_uuid': s.uuid, 'uuid': pl.uuid, 'dnp': pl.dnp, 'fields': pl.fields,
              'pins': dict(pl.nets)} for s in p.sheets for pl in s.symbols]
    with open(os.path.join(HERE, 'design_netlist.json'), 'w', encoding='utf-8') as f:
        json.dump({'project': p.name, 'root_uuid': p.root_uuid, 'components': comps}, f, indent=1)
    print(f'{len(comps)} components, {len(p.netlist())} nets written')
    if '--no-check' not in sys.argv:
        from kicadgen.netcheck import compare, export_netlist, exported_nets
        problems = compare(p.netlist(), exported_nets(export_netlist(os.path.join(HERE, f'{NAME}.kicad_sch'))))
        print('\n'.join(problems) if problems else 'net list check: KiCad connectivity matches design')
        sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
