"""3D models for footprints whose stock KiCad model does not exist.

The STEP files are generated by tools/models3d.py into PCB/elara.3dshapes/.
kicadgen.pcb swaps them in when it places a footprint (a footprint's 3D model is
not part of KiCad's "footprint differs from library" check).
"""

MODEL_DIR = '${KIPRJMOD}/../elara.3dshapes'

# footprint name -> model file
MODELS = {
    'Molex_Micro-Fit_3.0_43650-0200_1x02_P3.00mm_Horizontal': 'Molex_Micro-Fit_3.0_43650-0200_Horizontal.step',
    'TestPoint_Keystone_5000-5004_Miniature': 'Keystone_5000_TestPoint.step',
    'Transformer_Pulse_4Pin_W7.62mm': 'Newava_S22083.step',
    'Turret_PTFE_D3.0mm_Drill1.6mm': 'Turret_PTFE_D3.0mm.step',
    'Converter_ACDC_MeanWell_IRM-05-xx_THT': 'MeanWell_IRM-05-xx_THT.step',
    'Fuseholder_Clip-5x20mm_Bel_FC-203-22_Lateral_P17.80x5.00mm_D1.17mm_Horizontal':
        'Fuse_5x20_Bel_FC-203-22_pair.step',
    'Oscillator_SMD_SiT_PQFN-4Pin_3.2x2.5mm': 'Oscillator_SiT_PQFN-4Pin_3.2x2.5mm.step',
}
